FROM eclipse-temurin:11.0.17_8-jre
WORKDIR /eventsim_app

COPY ./scripts/eventsim.sh /eventsim_app/eventsim.sh
COPY ./bin/eventsim-assembly-2.0.jar /eventsim_app/eventsim-assembly-2.0.jar
ENTRYPOINT ["./eventsim.sh"]