name: SQLFluff lint dbt data models

on:
  pull_request:
    branches:
      - main
    paths:
      - "pipeline/transforms/models/**"

jobs:
  sqlfluff-lint-models:
    name: Lint dbt models using SQLFluff
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.8]
    # Set environment variables used throughout workflow
    env:
      DBT_PROFILES_DIR: ./

      # SPECIFY database connection credentials as env vars below.
      # Env var values to be fetched from as GitHub Secrets.
      # HIGHLY recommended you use a unique set of connection credentials for this worklfow alone.

      DBT_GOOGLE_BIGQUERY_KEYFILE: dbt-service-account.json
      DBT_GCP_PROJECT: ${{ secrets.DBT_GOOGLE_PROJECT }}
      DBT_BIGQUERY_DATASET: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET }}
      DBT_GCS_BUCKET_NAME: ${{ secrets.DBT_GCS_BUCKET_NAME }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Authenticate using service account
        shell: bash -l {0}
        run: |
          cd pipeline/transforms
          echo "$KEYFILE" > dbt-service-account.json
        env:
          KEYFILE: ${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: python -m pip install dbt-bigquery sqlfluff-templater-dbt

      - name: Lint dbt sql files with sqlfluff.
        shell: bash -l {0}
        run: |
          cd pipeline/transforms
          dbt deps
          sqlfluff lint --format github-annotation --annotation-level failure --nofail ./models > annotations.json

      - name: Annotate
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"
